---

- name: "Configuration play for app deployment." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  roles:
    - deploy-backend
  environment:
    - DATABASE_URL: "{{ DATABASE_URL }}"
    - GIT_USERNAME: "{{ GIT_USERNAME }}"
    - GIT_PASSWORD: "{{ GIT_PASSWORD }}"