version: 2.1


jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            npm i
      - run:
          name: Backend Build
          command: |
            npm run lint
      - save_cache:
          paths: [node_modules]
          key: backend-build

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run: 
          name: Run Backend Test
          command: |
            npm run test

            
  scan:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run: 
          name: Run Backend Audit
          command: |
            npm audit fix --audit-level=critical



workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - scan:
          requires: [build]


